### ISSUE TITLE
Adopt layout from https://github.com/fulldecent/swift5-module-template

### ISSUE THREAD

**Issue by fulldecent** [tmdvs/TDBadgedCell#88]
(Posting issue to confirm it is in the project scope. I am planning to commit resources to work on this.)

---

A modern project layout for Swift modules is defined at https://github.com/fulldecent/swift5-module-template

# Work plan

- [ ] Study best practices at link above
- [ ] Apply the "Recipe" from the Swift 5 Module Template to this project
- [ ] Ensure that PR does not change the current development team

# Follow-on work

- [ ] Make a minor version feature release with this updated project
